"""
Sample DQ_CHECK_CONFIG rows mirroring the examples used throughout the
design conversation (ORDERS / ORDER_LINES / CUSTOMERS). Used by
DemoConfigLoader for `python main.py --demo`.
"""

SAMPLE_CONFIG_ROWS = [
    {
        "CHECK_ID": "201", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDERS", "COLUMN_NAME": "CUSTOMER_ID",
        "NULL_CHECK_ACTIVE": True, "NULL_THRESHOLD": 0, "NULL_THRESHOLD_TYPE": "COUNT",
        "REFERENCE_TABLE": "SALES.PUBLIC.CUSTOMERS", "REFERENCE_COLUMN": "CUSTOMER_ID",
        "REF_THRESHOLD": 0, "REF_THRESHOLD_TYPE": "COUNT",
        "ROW_IDENTIFIER_COLUMNS": ["ORDER_ID"],
        "CRITICALITY": "CRITICAL", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "HOURLY",
    },
    {
        "CHECK_ID": "202", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDER_LINES", "COLUMN_NAME": None,
        "DUPLICATE_KEY_COLUMNS": ["ORDER_ID", "LINE_NO"], "DUPLICATE_THRESHOLD": 0,
        "DUPLICATE_THRESHOLD_TYPE": "COUNT",
        "ROW_IDENTIFIER_COLUMNS": ["ORDER_ID", "LINE_NO"],
        "CRITICALITY": "CRITICAL", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "HOURLY",
    },
    {
        "CHECK_ID": "203", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDERS", "COLUMN_NAME": "ORDER_AMOUNT",
        "NULL_CHECK_ACTIVE": True, "NULL_THRESHOLD": 0, "NULL_THRESHOLD_TYPE": "COUNT",
        "LOWER_BOUND": 0, "UPPER_BOUND": 100000, "RANGE_THRESHOLD": 1.0, "RANGE_THRESHOLD_TYPE": "PERCENT",
        "OUTLIER_SENSITIVITY": 3, "OUTLIER_THRESHOLD": 1.0, "OUTLIER_THRESHOLD_TYPE": "PERCENT",
        "OUTLIER_TEMPLATE_ID": "OUTLIER_ZSCORE",
        "ROW_IDENTIFIER_COLUMNS": ["ORDER_ID"],
        "CRITICALITY": "WARN", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "HOURLY",
    },
    {
        "CHECK_ID": "204", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "CUSTOMERS", "COLUMN_NAME": "EMAIL",
        "REGEX_PATTERN": r"^[\w.%-]+@[\w.-]+\.\w+$", "TYPE_THRESHOLD": 2.0, "TYPE_THRESHOLD_TYPE": "PERCENT",
        "ROW_IDENTIFIER_COLUMNS": ["CUSTOMER_ID"],
        "CRITICALITY": "WARN", "CHECK_STATUS": "SHADOW", "SCHEDULE_GROUP": "DAILY",
    },
    {
        "CHECK_ID": "205", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDERS", "COLUMN_NAME": "ORDER_STATUS",
        "ALLOWED_VALUES": ["OPEN", "CLOSED", "PENDING", "CANCELLED"],
        "CHECKLIST_THRESHOLD": 0.5, "CHECKLIST_THRESHOLD_TYPE": "PERCENT",
        "ROW_IDENTIFIER_COLUMNS": ["ORDER_ID"],
        "CRITICALITY": "WARN", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "HOURLY",
    },
    {
        "CHECK_ID": "206", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDERS", "COLUMN_NAME": None,
        "RECON_SOURCE_SQL": "SELECT COUNT(*) FROM SALES.PUBLIC.ORDERS",
        "RECON_TARGET_SQL": "SELECT COUNT(*) FROM SALES.STAGING.ORDERS_SRC",
        "RECON_TOLERANCE_PCT": 0.5,
        "CRITICALITY": "CRITICAL", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "DAILY",
    },
    {
        "CHECK_ID": "207", "DATABASE_NAME": "SALES", "SCHEMA_NAME": "PUBLIC",
        "TABLE_NAME": "ORDERS", "COLUMN_NAME": None,
        "CUSTOM_SQL": (
            "SELECT COUNT(*) AS TOTAL_ROWS, "
            "COUNT_IF(SHIP_DATE < ORDER_DATE) AS FAILED_ROWS FROM SALES.PUBLIC.ORDERS"
        ),
        "CUSTOM_THRESHOLD": 0, "CUSTOM_THRESHOLD_TYPE": "COUNT",
        "ROW_IDENTIFIER_COLUMNS": ["ORDER_ID"],
        "CRITICALITY": "CRITICAL", "CHECK_STATUS": "ACTIVE", "SCHEDULE_GROUP": "DAILY",
    },
]
